### PR TITLE
QUICK-24: Add AssignedKey KeyType

### PR DESCRIPTION
**Pull request by MordantWastrel**
https://ortussolutions.atlassian.net/browse/QUICK-24

### CODE REVIEW

**Comment by elpete** [comment]
Looks good.  Can you add a test for this, please?

**Comment by MordantWastrel** [comment]
The current tests will not run on MSSQL:

If I create a datasource called 'quick' but don't create the DB, Lucee throws the error 'Cannot open database "quick" requested by the login. The login failed. '

If I create the datasource but don't create the DB, I get 'Cannot drop database "quick" because it is currently in use.'

**Comment by elpete** [comment]
I should document this for running the tests, but please use a MySQL datasource.  Docker is a great option if you need one locally:

```
docker run -d --name=quick --env MYSQL_DATABASE=quick --env MYSQL_ROOT_PASSWORD=quick -p 3306:3306 mysql:5
```

**Comment by MordantWastrel** [comment]
That's easy enough, but is there documentation somewhere on the proper procedure for testing coldbox modules? In the past it's been a guessing game of reading Application.cfc, figuring out where to put Coldbox, when to clone a github repo and when to use Forgebox. I know it isn't especially difficult from having done it in the past, but I don't remember offhand what I did and it would grease the wheels on opening this stuff up to have an authoritative guide for module tests (as there is for Coldbox).

**Comment by elpete** [comment]
The right answer is it needs to be a part of the README.md for the repo.  That way anyone that clones the repo can run the tests.  I'll work on adding that as well as a `docker-compose.yml` file for making it as painless as possible.

**Comment by elpete** [comment]
https://ortussolutions.atlassian.net/browse/QUICK-25

**Pull request merged**
