### PR TITLE
ACF compatibility: Force generated key to be an integer

### PR DESCRIPTION
**Pull request by homestar9**
See https://github.com/coldbox-modules/quick/issues/200

### CODE REVIEW

**Comment by elpete** [comment]
Does the PR address your concerns raised [here](https://github.com/coldbox-modules/quick/issues/200#issuecomment-1279347568)?

**Comment by homestar9** [comment]
Yes it does.  However, there's still a problem for those using big integers and ACF.  Both `val()` and `int()` don't work for very big numbers.

**Comment by elpete** [comment]
What is the approach using Java's `BigInteger`?  Could we do that?

**Comment by homestar9** [comment]
> What is the approach using Java's `BigInteger`? Could we do that?

I don't have any experience with `java.math.BigInteger`, but I'll play around with it to see if I can create something that works.  I would be concerned about any possible overhead performance issues, though, since most users will be using normal integers.

**Comment by homestar9** [comment]
`BigInteger` may not be the way to go.   `precisionEvaluate()` may work, but doesn't solve the original intent of using `val()` to always return a number. Therefore, perhaps the better solution is something like this:
```
arguments.entity.assignAttribute( keyName,  ( isNumeric( generatedKey ) ? precisionEvaluate( generatedKey ) : val( generatedKey ) ) );
```

The above code should be tested to ensure it can handle a wide variety of numbers, but the idea here is that it first checks the `generatedKey` to see if it is numeric.  If so, run `precisionEvaluate()` on it to return an actual numeric object. This should fix the value coming back as a string instead.  If the `generatedString` is not a number, `val()` will turn it into 0 (or you can just return 0).

Still, I guess that  `precisionEvaluate()` must come at a performance cost, so if it were me, I would probably set up a new AutoBigIncrementingKeyType.cfc that uses `precisionEvaluate()` to avoid any performance hit for most users.  This PR will still work for most reasonably sized integers.

**Pull request merged**
