### PR TITLE
HasOneOrManyThrough CONCAT issue

### PR DESCRIPTION
**Pull request by MordantWastrel**
Add .when() qualifier in HasOneOrManyThrough so that CONCAT is only called with multiple keys

### CODE REVIEW

**Comment by elpete** [comment]
I think you need the `else` clause of when to do a normal select.

**Comment by MordantWastrel** [comment]
Just added that but am flying blind because the tests won't run for me locally:

```

Message | Page /testbox/system/reports/assets/js/jquery.js [F:\repos\quick\testbox\system\reports\assets\js\jquery.js] not found
-- | --
Mapping | /testbox
Stacktrace | The Error Occurred inF:\repos\quick\tests\index.cfm: line 5250: <meta name="generator" content="TestBox v#testbox.getVersion()#">51: <title>TestBox Global Runner</title>52: <script><cfinclude template="/testbox/system/reports/assets/js/jquery.js"></script>53: <script>54: $(document).ready(function() {

```
It is looking for `jquery.js` and there is only `jquery-3.3.1.min.js`

**Comment by elpete** [comment]
I’d try nuking the testbox folder and installing again to fix that.

Can you run `box run-script format` and push it up? Then it’s ready to go.

**Comment by MordantWastrel** [comment]
I had just done a fresh install of Testbox, but deleted it and reinstalled. No change.

When I ran `run-script format`, it modified 10 files with formatting changes. I ran cfformat just on the file I changed. It adjusted one other section besides the one I added.

I appreciate the desire for consistent formatting but it is problematic to try to deal with cfformat manually for a PR.

**Comment by MordantWastrel** [comment]
This just popped up again in Quick v4. It looks like this commit made it to 3.16 but not into 4?

**Pull request closed without merging**
