### PR TITLE
refactor(BaseEntity): Make internal properties more resistant to name clashes

### PR DESCRIPTION
**Pull request by elpete**
This commit changes almost all the internal property names and functions to better
avoid name clashes.  This involved prefixing all properties with an underscore
as well as eliminating almost all public methods that start with `set` or `get`.

BREAKING CHANGE: Any code that used internal functions of the `BaseEntity`
will need to update to the name function and property names.

### CODE REVIEW

**Comment by elpete** [comment]
@MordantWastrel @wpdebruin @jclausen 

I'd love to get your feedback on the above changes and how it might affect your development.

**Comment by MordantWastrel** [comment]
This looks great!

I don't think it's necessary a problem for fields like **key** and **keyType** -- while it's conceivable that there could be overlap with user code on those variables, I was more concerned with the **getThing()** functions. I'd have no trouble reserving key and keyType for Quick, though.

**Comment by wpdebruin** [comment]
I think it is a good idea, for me it makes things more clear.  I was not using quick (yet), so no problems here.

**Comment by Tropicalista** [comment]
I don't know if this is related, however I post here because there's no bug tracking.

If I create a 

`	property name="settings" type="struct";
`

when I try to insert a record, 

```   
 function setSettings( value ) {
        return setAttribute( "settings", serializeJSON(value) );
 } 
```

I got this error:

Messages: can't assign value to a Object of this type [String] with key automaticValidation

Template: | F:\Progetti\CodeCanyon\Refactoring\apiservertest\modules\quick\models\BaseEntity.cfc
-- | --
LINE: | 929: param settings.automaticValidation = false;

This is probably a name issue, because if I try to change name, it works great.

**Comment by elpete** [comment]
@Tropicalista That is exactly it.  That one has been changed in this PR as well.

**Pull request merged**
